### ISSUE TITLE
Inaccurate Contact Info In Contributing.md

### ISSUE THREAD

**Issue by scriptGenie** [Akash-Singh04/QuizQuest#21]
The username in the following section does not match the socials linked on owner's github profile:

>    Contact @Akash-Singh04 to get the .env file containing the firebase configurations. After getting the env file skip to step (d).

>    Alternatively Contact @Akash-Singh04 to get collaborator access to the firebase project that contains the User Authentication and Firebase Firestore Database. An email will be sent with the invitaion for the same.

Additionally these sections could specify which platform the preferred contact method can be found on.

**Comment by SkySingh04** [comment]
Please make a PR for the same!
