### ISSUE TITLE
Misnumbered Sections In Contributing.md

### ISSUE THREAD

**Issue by scriptGenie** [Akash-Singh04/QuizQuest#22]
Currently the steps are listed in the following order:

1. Clone the repository:
2. Install dependencies:
3. Firebase Configuration Setup
5. Steps to Set Firebase Environment Variables
5. Run the project:
6. Access the project locally at http://localhost:3000.

Suggest changing the first listed '5' to be '4'.

**Comment by SkySingh04** [comment]
Kindly make a PR for the same
